### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by allytrope** [lmdu/macaca#1]
Hi, I'm wanting to fork this project for my own SNV data. I noticed that all earlier versions had an MIT license. But the latest commit a64d168aa01f413f9d0fa512579fec0a311af60f is now missing the LICENSE file. Is the current version still intended to have the MIT license?

**Comment by lmdu** [comment]
Yes, it is still under MIT license.  You can use it by citing the paper https://doi.org/10.1093/database/baaa027

**Comment by allytrope** [comment]
Perfect! Thank you!
